# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scheduletool.bdware.proto.schedule_service_pb2 as schedule__service__pb2


class ScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadBalancingByNodes = channel.unary_unary(
                '/schedule.bdware.ScheduleService/LoadBalancingByNodes',
                request_serializer=schedule__service__pb2.LoadBalancingByNodesRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.LoadBalancingByNodesResponse.FromString,
                )


class ScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadBalancingByNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadBalancingByNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadBalancingByNodes,
                    request_deserializer=schedule__service__pb2.LoadBalancingByNodesRequest.FromString,
                    response_serializer=schedule__service__pb2.LoadBalancingByNodesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedule.bdware.ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadBalancingByNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schedule.bdware.ScheduleService/LoadBalancingByNodes',
            schedule__service__pb2.LoadBalancingByNodesRequest.SerializeToString,
            schedule__service__pb2.LoadBalancingByNodesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
