# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduletool/bdware/proto/schedule_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduletool/bdware/proto/schedule_service.proto',
  package='schedule.bdware',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0scheduletool/bdware/proto/schedule_service.proto\x12\x0fschedule.bdware\"E\n\x0b\x43lusterInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x05nodes\x18\x02 \x03(\x0b\x32\x19.schedule.bdware.NodeInfo\":\n\x08NodeInfo\x12\x0c\n\x04home\x18\x01 \x01(\t\x12\x0f\n\x07storage\x18\x02 \x01(\t\x12\x0f\n\x07traffic\x18\x03 \x01(\t\"0\n\x0c\x43ontractInfo\x12\x0f\n\x07storage\x18\x01 \x01(\t\x12\x0f\n\x07traffic\x18\x02 \x01(\t\"`\n\x1bLoadBalancingByNodesRequest\x12.\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\x1c.schedule.bdware.ClusterInfo\x12\x11\n\tthreshold\x18\x02 \x01(\x02\"Q\n\x10\x43ontractTransfer\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63luster_src\x18\x02 \x01(\t\x12\x13\n\x0b\x63luster_dst\x18\x03 \x01(\t\"h\n\x1cLoadBalancingByNodesResponse\x12\x34\n\ttransfers\x18\x01 \x03(\x0b\x32!.schedule.bdware.ContractTransfer\x12\x12\n\nerror_code\x18\x02 \x01(\x05\"\x91\x01\n\x1bQueryDeployedClusterRequest\x12.\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\x1c.schedule.bdware.ClusterInfo\x12\x11\n\tthreshold\x18\x02 \x01(\x02\x12/\n\x08\x63ontract\x18\x03 \x01(\x0b\x32\x1d.schedule.bdware.ContractInfo\"H\n\x1cQueryDeployedClusterResponse\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\x05\x32\xff\x01\n\x0fScheduleService\x12u\n\x14LoadBalancingByNodes\x12,.schedule.bdware.LoadBalancingByNodesRequest\x1a-.schedule.bdware.LoadBalancingByNodesResponse\"\x00\x12u\n\x14QueryDeployedCluster\x12,.schedule.bdware.QueryDeployedClusterRequest\x1a-.schedule.bdware.QueryDeployedClusterResponse\"\x00\x62\x06proto3'
)




_CLUSTERINFO = _descriptor.Descriptor(
  name='ClusterInfo',
  full_name='schedule.bdware.ClusterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='schedule.bdware.ClusterInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='schedule.bdware.ClusterInfo.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=138,
)


_NODEINFO = _descriptor.Descriptor(
  name='NodeInfo',
  full_name='schedule.bdware.NodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='home', full_name='schedule.bdware.NodeInfo.home', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storage', full_name='schedule.bdware.NodeInfo.storage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic', full_name='schedule.bdware.NodeInfo.traffic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=198,
)


_CONTRACTINFO = _descriptor.Descriptor(
  name='ContractInfo',
  full_name='schedule.bdware.ContractInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='storage', full_name='schedule.bdware.ContractInfo.storage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic', full_name='schedule.bdware.ContractInfo.traffic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=248,
)


_LOADBALANCINGBYNODESREQUEST = _descriptor.Descriptor(
  name='LoadBalancingByNodesRequest',
  full_name='schedule.bdware.LoadBalancingByNodesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusters', full_name='schedule.bdware.LoadBalancingByNodesRequest.clusters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='schedule.bdware.LoadBalancingByNodesRequest.threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=346,
)


_CONTRACTTRANSFER = _descriptor.Descriptor(
  name='ContractTransfer',
  full_name='schedule.bdware.ContractTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='schedule.bdware.ContractTransfer.contract_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_src', full_name='schedule.bdware.ContractTransfer.cluster_src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_dst', full_name='schedule.bdware.ContractTransfer.cluster_dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=429,
)


_LOADBALANCINGBYNODESRESPONSE = _descriptor.Descriptor(
  name='LoadBalancingByNodesResponse',
  full_name='schedule.bdware.LoadBalancingByNodesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transfers', full_name='schedule.bdware.LoadBalancingByNodesResponse.transfers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='schedule.bdware.LoadBalancingByNodesResponse.error_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=535,
)


_QUERYDEPLOYEDCLUSTERREQUEST = _descriptor.Descriptor(
  name='QueryDeployedClusterRequest',
  full_name='schedule.bdware.QueryDeployedClusterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusters', full_name='schedule.bdware.QueryDeployedClusterRequest.clusters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='schedule.bdware.QueryDeployedClusterRequest.threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contract', full_name='schedule.bdware.QueryDeployedClusterRequest.contract', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=683,
)


_QUERYDEPLOYEDCLUSTERRESPONSE = _descriptor.Descriptor(
  name='QueryDeployedClusterResponse',
  full_name='schedule.bdware.QueryDeployedClusterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='schedule.bdware.QueryDeployedClusterResponse.cluster_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='schedule.bdware.QueryDeployedClusterResponse.error_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=757,
)

_CLUSTERINFO.fields_by_name['nodes'].message_type = _NODEINFO
_LOADBALANCINGBYNODESREQUEST.fields_by_name['clusters'].message_type = _CLUSTERINFO
_LOADBALANCINGBYNODESRESPONSE.fields_by_name['transfers'].message_type = _CONTRACTTRANSFER
_QUERYDEPLOYEDCLUSTERREQUEST.fields_by_name['clusters'].message_type = _CLUSTERINFO
_QUERYDEPLOYEDCLUSTERREQUEST.fields_by_name['contract'].message_type = _CONTRACTINFO
DESCRIPTOR.message_types_by_name['ClusterInfo'] = _CLUSTERINFO
DESCRIPTOR.message_types_by_name['NodeInfo'] = _NODEINFO
DESCRIPTOR.message_types_by_name['ContractInfo'] = _CONTRACTINFO
DESCRIPTOR.message_types_by_name['LoadBalancingByNodesRequest'] = _LOADBALANCINGBYNODESREQUEST
DESCRIPTOR.message_types_by_name['ContractTransfer'] = _CONTRACTTRANSFER
DESCRIPTOR.message_types_by_name['LoadBalancingByNodesResponse'] = _LOADBALANCINGBYNODESRESPONSE
DESCRIPTOR.message_types_by_name['QueryDeployedClusterRequest'] = _QUERYDEPLOYEDCLUSTERREQUEST
DESCRIPTOR.message_types_by_name['QueryDeployedClusterResponse'] = _QUERYDEPLOYEDCLUSTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClusterInfo = _reflection.GeneratedProtocolMessageType('ClusterInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERINFO,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.ClusterInfo)
  })
_sym_db.RegisterMessage(ClusterInfo)

NodeInfo = _reflection.GeneratedProtocolMessageType('NodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.NodeInfo)
  })
_sym_db.RegisterMessage(NodeInfo)

ContractInfo = _reflection.GeneratedProtocolMessageType('ContractInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTINFO,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.ContractInfo)
  })
_sym_db.RegisterMessage(ContractInfo)

LoadBalancingByNodesRequest = _reflection.GeneratedProtocolMessageType('LoadBalancingByNodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADBALANCINGBYNODESREQUEST,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.LoadBalancingByNodesRequest)
  })
_sym_db.RegisterMessage(LoadBalancingByNodesRequest)

ContractTransfer = _reflection.GeneratedProtocolMessageType('ContractTransfer', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTTRANSFER,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.ContractTransfer)
  })
_sym_db.RegisterMessage(ContractTransfer)

LoadBalancingByNodesResponse = _reflection.GeneratedProtocolMessageType('LoadBalancingByNodesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADBALANCINGBYNODESRESPONSE,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.LoadBalancingByNodesResponse)
  })
_sym_db.RegisterMessage(LoadBalancingByNodesResponse)

QueryDeployedClusterRequest = _reflection.GeneratedProtocolMessageType('QueryDeployedClusterRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYDEPLOYEDCLUSTERREQUEST,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.QueryDeployedClusterRequest)
  })
_sym_db.RegisterMessage(QueryDeployedClusterRequest)

QueryDeployedClusterResponse = _reflection.GeneratedProtocolMessageType('QueryDeployedClusterResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYDEPLOYEDCLUSTERRESPONSE,
  '__module__' : 'scheduletool.bdware.proto.schedule_service_pb2'
  # @@protoc_insertion_point(class_scope:schedule.bdware.QueryDeployedClusterResponse)
  })
_sym_db.RegisterMessage(QueryDeployedClusterResponse)



_SCHEDULESERVICE = _descriptor.ServiceDescriptor(
  name='ScheduleService',
  full_name='schedule.bdware.ScheduleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=760,
  serialized_end=1015,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadBalancingByNodes',
    full_name='schedule.bdware.ScheduleService.LoadBalancingByNodes',
    index=0,
    containing_service=None,
    input_type=_LOADBALANCINGBYNODESREQUEST,
    output_type=_LOADBALANCINGBYNODESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryDeployedCluster',
    full_name='schedule.bdware.ScheduleService.QueryDeployedCluster',
    index=1,
    containing_service=None,
    input_type=_QUERYDEPLOYEDCLUSTERREQUEST,
    output_type=_QUERYDEPLOYEDCLUSTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULESERVICE)

DESCRIPTOR.services_by_name['ScheduleService'] = _SCHEDULESERVICE

# @@protoc_insertion_point(module_scope)
